# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4094f7f2a01313db6023dcd8c84ea65e01e37bcf19a7e10bb1f8e740b4e94793aa99139e5dcab3e7345de21697e610eb8ec9409730255d890b992943cc5651ca

test:
  secret_key_base: df3b25dcb5ff822098c79b7ad573058d9cc86d04e52bf113b11ab7b7a902e3df17f8178f1af95a031334c2ed2f1f023f75c35e7951b0a258854e878f7b3e6ec1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
